---
- name: Playbook para hacer el deploy de la aplicaci贸n web moodle
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Descargar el c贸digo fuente de moodle
      get_url:
        url: https://github.com/moodle/moodle/archive/refs/tags/v4.3.1.zip 
        dest: /tmp/moodle-4.3.1.zip
        mode: 0755

    - name: Instalar unzip
      apt: 
        name: unzip
        state: present

    - name: Descomprimir el paquete de moodle
      unarchive:
        src: /tmp/moodle-4.3.1.zip  
        dest: /tmp
        remote_src: yes

    - name: Eliminar el directorio de instalaci贸n
      file:
        path: /var/www/html/moodle
        state: absent

    - name: Crear el directorio de instalaci贸n
      file:
        path: /var/www/html/moodle
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

    - name: Copiar contenido de moodle-4.3.1 a /var/www/html/moodle
      copy:
        src: /tmp/moodle-4.3.1/
        dest: /var/www/html/moodle
        remote_src: true
        force: yes

    - name: Modificar los permisos del directorio /var/www/html/moodle
      file:
        path: /var/www/html/moodle
        owner: www-data
        group: www-data
        recurse: yes
        mode: 0755

    - name: Modificar los permisos del directorio /var/moodledata
      file:
        path: /var/moodledata
        owner: www-data
        group: www-data
        recurse: yes
        mode: 0755
        
    - name: Instalar moodle desde PHP CLI
      command: >
        sudo -u www-data php /var/www/html/moodle/admin/cli/install.php
        --wwwroot={{ moodle.www_root }}
        --dataroot={{ moodle.data_root }}
        --dbtype={{ moodle.type }}
        --dbhost={{ moodle.host }}
        --dbname={{ db.name }}
        --dbuser={{ db.user }}
        --dbpass={{ db.password }}
        --fullname="{{ moodle.fullname }}"
        --shortname="{{ moodle.shortname }}"
        --summary="{{ moodle.summary }}"
        --adminuser={{ moodle.admin_user }}
        --adminpass={{ moodle.admin_pass }}
        --adminemail={{ moodle.admin_email }}
        --non-interactive
        --agree-license
      args:
        chdir: /var/www/html/moodle

    - name: Configurar cron para Moodle
      become: yes
      ansible.builtin.cron:
        name: "Moodle Cron Job"
        minute: "*"
        job: "/usr/bin/php /var/www/html/moodle/admin/cli/cron.php"
        state: present

    - name: Reiniciar servicio cron 
      become: yes
      ansible.builtin.service:
        name: cron
        state: restarted
        enabled: yes