---
- name: Configurar Certbot y solicitar certificado SSL
  hosts: frontend
  become: yes
  vars_files:
    - ../vars/variables.yml 

  tasks:
    # Instalar snapd si no est치 presente
    - name: Instalar snapd si no est치 presente
      apt:
        name: snapd
        state: present

    # Instalar el paquete base de snap si no est치
    - name: Instalar core de snap si no est치 presente
      snap:
        name: core
        state: present

    # Eliminar instalaciones anteriores de certbot con apt
    - name: Eliminar Certbot instalado con apt (si existe)
      apt:
        name: certbot
        state: absent

    # Instalar Certbot con snap
    - name: Instalar Certbot usando snap
      snap:
        name: certbot
        state: present

    # Verificar las variables certbot
    - name: Verificar las variables certbot
      debug:
        msg: "Email: {{ certbot.le_email }}, Domain: {{ certbot.le_domain }}"

    # Solicitar un certificado SSL para el dominio con Certbot
    - name: Solicitar certificado SSL para el dominio con Certbot
      command: >
        certbot --apache
        -m "{{ certbot.le_email }}"
        --agree-tos
        --no-eff-email
        -d "{{ certbot.le_domain }}"
        --non-interactive